/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrgBalanceRouteImport } from './routes/admin/org-balance'
import { Route as AdminModelPricingRouteImport } from './routes/admin/model-pricing'
import { Route as AdminCreditAdjustmentRouteImport } from './routes/admin/credit-adjustment'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOutboundRouteImport } from './routes/_app/outbound'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppFlowsRouteImport } from './routes/_app/flows'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBroadcastRouteImport } from './routes/_app/broadcast'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppTopUpIndexRouteImport } from './routes/_app/top-up/index'
import { Route as AppSubscriptionIndexRouteImport } from './routes/_app/subscription/index'
import { Route as AppDevelopersIndexRouteImport } from './routes/_app/developers/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppInstagramInboxRouteImport } from './routes/_app/instagram/inbox'
import { Route as AppDevelopersWebhooksRouteImport } from './routes/_app/developers/webhooks'
import { Route as AppDevelopersMessagesSentByApiRouteImport } from './routes/_app/developers/messages-sent-by-api'
import { Route as AppDevelopersApiToolsRouteImport } from './routes/_app/developers/api-tools'
import { Route as AppDevelopersApiDocumentationRouteImport } from './routes/_app/developers/api-documentation'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppConversationsConversationIdRouteImport } from './routes/_app/conversations/$conversationId'
import { Route as AppChannelsWhatsappRouteImport } from './routes/_app/channels/whatsapp'
import { Route as AppChannelsTiktokRouteImport } from './routes/_app/channels/tiktok'
import { Route as AppChannelsTelegramRouteImport } from './routes/_app/channels/telegram'
import { Route as AppChannelsLivechatRouteImport } from './routes/_app/channels/livechat'
import { Route as AppChannelsLineRouteImport } from './routes/_app/channels/line'
import { Route as AppChannelsFacebookRouteImport } from './routes/_app/channels/facebook'
import { Route as AppChannelsCustomRouteImport } from './routes/_app/channels/custom'
import { Route as AppChannelsBotRouteImport } from './routes/_app/channels/bot'
import { Route as AppAppsMetaAdsTrackerRouteImport } from './routes/_app/apps/meta-ads-tracker'
import { Route as AppAppsAppSlugRouteImport } from './routes/_app/apps/$appSlug'
import { Route as AppAiAgentsAgentIdRouteImport } from './routes/_app/ai-agents/$agentId'
import { Route as AppChannelsInstagramIndexRouteImport } from './routes/_app/channels/instagram/index'
import { Route as AppDevelopersApiToolsNewRouteImport } from './routes/_app/developers/api-tools/new'
import { Route as AppChannelsWhatsappSuccessRouteImport } from './routes/_app/channels/whatsapp/success'
import { Route as AppChannelsWhatsappChannelIdRouteImport } from './routes/_app/channels/whatsapp/$channelId'
import { Route as AppChannelsTiktokInboxIdRouteImport } from './routes/_app/channels/tiktok/$inboxId'
import { Route as AppChannelsInstagramInboxIdRouteImport } from './routes/_app/channels/instagram/$inboxId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgBalanceRoute = AdminOrgBalanceRouteImport.update({
  id: '/org-balance',
  path: '/org-balance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelPricingRoute = AdminModelPricingRouteImport.update({
  id: '/model-pricing',
  path: '/model-pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditAdjustmentRoute = AdminCreditAdjustmentRouteImport.update({
  id: '/credit-adjustment',
  path: '/credit-adjustment',
  getParentRoute: () => AdminRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOutboundRoute = AppOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppTopUpIndexRoute = AppTopUpIndexRouteImport.update({
  id: '/top-up/',
  path: '/top-up/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionIndexRoute = AppSubscriptionIndexRouteImport.update({
  id: '/subscription/',
  path: '/subscription/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersIndexRoute = AppDevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramInboxRoute = AppInstagramInboxRouteImport.update({
  id: '/instagram/inbox',
  path: '/instagram/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersWebhooksRoute = AppDevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersMessagesSentByApiRoute =
  AppDevelopersMessagesSentByApiRouteImport.update({
    id: '/developers/messages-sent-by-api',
    path: '/developers/messages-sent-by-api',
    getParentRoute: () => AppRoute,
  } as any)
const AppDevelopersApiToolsRoute = AppDevelopersApiToolsRouteImport.update({
  id: '/developers/api-tools',
  path: '/developers/api-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersApiDocumentationRoute =
  AppDevelopersApiDocumentationRouteImport.update({
    id: '/developers/api-documentation',
    path: '/developers/api-documentation',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppChannelsWhatsappRoute = AppChannelsWhatsappRouteImport.update({
  id: '/channels/whatsapp',
  path: '/channels/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsTiktokRoute = AppChannelsTiktokRouteImport.update({
  id: '/channels/tiktok',
  path: '/channels/tiktok',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsTelegramRoute = AppChannelsTelegramRouteImport.update({
  id: '/channels/telegram',
  path: '/channels/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLivechatRoute = AppChannelsLivechatRouteImport.update({
  id: '/channels/livechat',
  path: '/channels/livechat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLineRoute = AppChannelsLineRouteImport.update({
  id: '/channels/line',
  path: '/channels/line',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsFacebookRoute = AppChannelsFacebookRouteImport.update({
  id: '/channels/facebook',
  path: '/channels/facebook',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsCustomRoute = AppChannelsCustomRouteImport.update({
  id: '/channels/custom',
  path: '/channels/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsBotRoute = AppChannelsBotRouteImport.update({
  id: '/channels/bot',
  path: '/channels/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsMetaAdsTrackerRoute = AppAppsMetaAdsTrackerRouteImport.update({
  id: '/apps/meta-ads-tracker',
  path: '/apps/meta-ads-tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppSlugRoute = AppAppsAppSlugRouteImport.update({
  id: '/apps/$appSlug',
  path: '/apps/$appSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentsAgentIdRoute = AppAiAgentsAgentIdRouteImport.update({
  id: '/ai-agents/$agentId',
  path: '/ai-agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsInstagramIndexRoute =
  AppChannelsInstagramIndexRouteImport.update({
    id: '/channels/instagram/',
    path: '/channels/instagram/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDevelopersApiToolsNewRoute =
  AppDevelopersApiToolsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppDevelopersApiToolsRoute,
  } as any)
const AppChannelsWhatsappSuccessRoute =
  AppChannelsWhatsappSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)
const AppChannelsWhatsappChannelIdRoute =
  AppChannelsWhatsappChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)
const AppChannelsTiktokInboxIdRoute =
  AppChannelsTiktokInboxIdRouteImport.update({
    id: '/$inboxId',
    path: '/$inboxId',
    getParentRoute: () => AppChannelsTiktokRoute,
  } as any)
const AppChannelsInstagramInboxIdRoute =
  AppChannelsInstagramInboxIdRouteImport.update({
    id: '/channels/instagram/$inboxId',
    path: '/channels/instagram/$inboxId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/select-org': typeof SelectOrgRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRoute
  '/help': typeof AppHelpRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/metrics': typeof AppMetricsRoute
  '/orders': typeof AppOrdersRoute
  '/outbound': typeof AppOutboundRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/tickets': typeof AppTicketsRoute
  '/admin/credit-adjustment': typeof AdminCreditAdjustmentRoute
  '/admin/model-pricing': typeof AdminModelPricingRoute
  '/admin/org-balance': typeof AdminOrgBalanceRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/tiktok': typeof AppChannelsTiktokRouteWithChildren
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/instagram/inbox': typeof AppInstagramInboxRoute
  '/apps/': typeof AppAppsIndexRoute
  '/billing/': typeof AppBillingIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/developers/': typeof AppDevelopersIndexRoute
  '/subscription/': typeof AppSubscriptionIndexRoute
  '/top-up/': typeof AppTopUpIndexRoute
  '/channels/instagram/$inboxId': typeof AppChannelsInstagramInboxIdRoute
  '/channels/tiktok/$inboxId': typeof AppChannelsTiktokInboxIdRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
  '/channels/instagram/': typeof AppChannelsInstagramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/select-org': typeof SelectOrgRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/automation': typeof AppAutomationRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRoute
  '/help': typeof AppHelpRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/metrics': typeof AppMetricsRoute
  '/orders': typeof AppOrdersRoute
  '/outbound': typeof AppOutboundRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/tickets': typeof AppTicketsRoute
  '/admin/credit-adjustment': typeof AdminCreditAdjustmentRoute
  '/admin/model-pricing': typeof AdminModelPricingRoute
  '/admin/org-balance': typeof AdminOrgBalanceRoute
  '/admin': typeof AdminIndexRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/tiktok': typeof AppChannelsTiktokRouteWithChildren
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/instagram/inbox': typeof AppInstagramInboxRoute
  '/apps': typeof AppAppsIndexRoute
  '/billing': typeof AppBillingIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/developers': typeof AppDevelopersIndexRoute
  '/subscription': typeof AppSubscriptionIndexRoute
  '/top-up': typeof AppTopUpIndexRoute
  '/channels/instagram/$inboxId': typeof AppChannelsInstagramInboxIdRoute
  '/channels/tiktok/$inboxId': typeof AppChannelsTiktokInboxIdRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
  '/channels/instagram': typeof AppChannelsInstagramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/create-org': typeof CreateOrgRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/select-org': typeof SelectOrgRoute
  '/terms': typeof TermsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flows': typeof AppFlowsRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/outbound': typeof AppOutboundRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/admin/credit-adjustment': typeof AdminCreditAdjustmentRoute
  '/admin/model-pricing': typeof AdminModelPricingRoute
  '/admin/org-balance': typeof AdminOrgBalanceRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/_app/apps/$appSlug': typeof AppAppsAppSlugRoute
  '/_app/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/_app/channels/bot': typeof AppChannelsBotRoute
  '/_app/channels/custom': typeof AppChannelsCustomRoute
  '/_app/channels/facebook': typeof AppChannelsFacebookRoute
  '/_app/channels/line': typeof AppChannelsLineRoute
  '/_app/channels/livechat': typeof AppChannelsLivechatRoute
  '/_app/channels/telegram': typeof AppChannelsTelegramRoute
  '/_app/channels/tiktok': typeof AppChannelsTiktokRouteWithChildren
  '/_app/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/_app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/_app/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/_app/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/_app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/_app/instagram/inbox': typeof AppInstagramInboxRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/developers/': typeof AppDevelopersIndexRoute
  '/_app/subscription/': typeof AppSubscriptionIndexRoute
  '/_app/top-up/': typeof AppTopUpIndexRoute
  '/_app/channels/instagram/$inboxId': typeof AppChannelsInstagramInboxIdRoute
  '/_app/channels/tiktok/$inboxId': typeof AppChannelsTiktokInboxIdRoute
  '/_app/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/_app/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/_app/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
  '/_app/channels/instagram/': typeof AppChannelsInstagramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create-org'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-org'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automation'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/flows'
    | '/help'
    | '/integration'
    | '/knowledge'
    | '/metrics'
    | '/orders'
    | '/outbound'
    | '/pipeline'
    | '/settings'
    | '/team'
    | '/templates'
    | '/tickets'
    | '/admin/credit-adjustment'
    | '/admin/model-pricing'
    | '/admin/org-balance'
    | '/admin/'
    | '/ai-agents/$agentId'
    | '/apps/$appSlug'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/tiktok'
    | '/channels/whatsapp'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/instagram/inbox'
    | '/apps/'
    | '/billing/'
    | '/customers/'
    | '/developers/'
    | '/subscription/'
    | '/top-up/'
    | '/channels/instagram/$inboxId'
    | '/channels/tiktok/$inboxId'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
    | '/channels/instagram/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-org'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-org'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automation'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/flows'
    | '/help'
    | '/integration'
    | '/knowledge'
    | '/metrics'
    | '/orders'
    | '/outbound'
    | '/pipeline'
    | '/settings'
    | '/team'
    | '/templates'
    | '/tickets'
    | '/admin/credit-adjustment'
    | '/admin/model-pricing'
    | '/admin/org-balance'
    | '/admin'
    | '/ai-agents/$agentId'
    | '/apps/$appSlug'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/tiktok'
    | '/channels/whatsapp'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/instagram/inbox'
    | '/apps'
    | '/billing'
    | '/customers'
    | '/developers'
    | '/subscription'
    | '/top-up'
    | '/channels/instagram/$inboxId'
    | '/channels/tiktok/$inboxId'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
    | '/channels/instagram'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/create-org'
    | '/login'
    | '/privacy'
    | '/register'
    | '/select-org'
    | '/terms'
    | '/_app/ai'
    | '/_app/analytics'
    | '/_app/automation'
    | '/_app/broadcast'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/flows'
    | '/_app/help'
    | '/_app/integration'
    | '/_app/knowledge'
    | '/_app/metrics'
    | '/_app/orders'
    | '/_app/outbound'
    | '/_app/pipeline'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/templates'
    | '/_app/tickets'
    | '/admin/credit-adjustment'
    | '/admin/model-pricing'
    | '/admin/org-balance'
    | '/admin/'
    | '/_app/ai-agents/$agentId'
    | '/_app/apps/$appSlug'
    | '/_app/apps/meta-ads-tracker'
    | '/_app/channels/bot'
    | '/_app/channels/custom'
    | '/_app/channels/facebook'
    | '/_app/channels/line'
    | '/_app/channels/livechat'
    | '/_app/channels/telegram'
    | '/_app/channels/tiktok'
    | '/_app/channels/whatsapp'
    | '/_app/conversations/$conversationId'
    | '/_app/customers/$customerId'
    | '/_app/developers/api-documentation'
    | '/_app/developers/api-tools'
    | '/_app/developers/messages-sent-by-api'
    | '/_app/developers/webhooks'
    | '/_app/instagram/inbox'
    | '/_app/apps/'
    | '/_app/billing/'
    | '/_app/customers/'
    | '/_app/developers/'
    | '/_app/subscription/'
    | '/_app/top-up/'
    | '/_app/channels/instagram/$inboxId'
    | '/_app/channels/tiktok/$inboxId'
    | '/_app/channels/whatsapp/$channelId'
    | '/_app/channels/whatsapp/success'
    | '/_app/developers/api-tools/new'
    | '/_app/channels/instagram/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CreateOrgRoute: typeof CreateOrgRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SelectOrgRoute: typeof SelectOrgRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-balance': {
      id: '/admin/org-balance'
      path: '/org-balance'
      fullPath: '/admin/org-balance'
      preLoaderRoute: typeof AdminOrgBalanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-pricing': {
      id: '/admin/model-pricing'
      path: '/model-pricing'
      fullPath: '/admin/model-pricing'
      preLoaderRoute: typeof AdminModelPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credit-adjustment': {
      id: '/admin/credit-adjustment'
      path: '/credit-adjustment'
      fullPath: '/admin/credit-adjustment'
      preLoaderRoute: typeof AdminCreditAdjustmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outbound': {
      id: '/_app/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AppOutboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows': {
      id: '/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/top-up/': {
      id: '/_app/top-up/'
      path: '/top-up'
      fullPath: '/top-up/'
      preLoaderRoute: typeof AppTopUpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription/': {
      id: '/_app/subscription/'
      path: '/subscription'
      fullPath: '/subscription/'
      preLoaderRoute: typeof AppSubscriptionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/': {
      id: '/_app/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof AppDevelopersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram/inbox': {
      id: '/_app/instagram/inbox'
      path: '/instagram/inbox'
      fullPath: '/instagram/inbox'
      preLoaderRoute: typeof AppInstagramInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/webhooks': {
      id: '/_app/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof AppDevelopersWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/messages-sent-by-api': {
      id: '/_app/developers/messages-sent-by-api'
      path: '/developers/messages-sent-by-api'
      fullPath: '/developers/messages-sent-by-api'
      preLoaderRoute: typeof AppDevelopersMessagesSentByApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-tools': {
      id: '/_app/developers/api-tools'
      path: '/developers/api-tools'
      fullPath: '/developers/api-tools'
      preLoaderRoute: typeof AppDevelopersApiToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-documentation': {
      id: '/_app/developers/api-documentation'
      path: '/developers/api-documentation'
      fullPath: '/developers/api-documentation'
      preLoaderRoute: typeof AppDevelopersApiDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations/$conversationId': {
      id: '/_app/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/whatsapp': {
      id: '/_app/channels/whatsapp'
      path: '/channels/whatsapp'
      fullPath: '/channels/whatsapp'
      preLoaderRoute: typeof AppChannelsWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/tiktok': {
      id: '/_app/channels/tiktok'
      path: '/channels/tiktok'
      fullPath: '/channels/tiktok'
      preLoaderRoute: typeof AppChannelsTiktokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/telegram': {
      id: '/_app/channels/telegram'
      path: '/channels/telegram'
      fullPath: '/channels/telegram'
      preLoaderRoute: typeof AppChannelsTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/livechat': {
      id: '/_app/channels/livechat'
      path: '/channels/livechat'
      fullPath: '/channels/livechat'
      preLoaderRoute: typeof AppChannelsLivechatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/line': {
      id: '/_app/channels/line'
      path: '/channels/line'
      fullPath: '/channels/line'
      preLoaderRoute: typeof AppChannelsLineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/facebook': {
      id: '/_app/channels/facebook'
      path: '/channels/facebook'
      fullPath: '/channels/facebook'
      preLoaderRoute: typeof AppChannelsFacebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/custom': {
      id: '/_app/channels/custom'
      path: '/channels/custom'
      fullPath: '/channels/custom'
      preLoaderRoute: typeof AppChannelsCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/bot': {
      id: '/_app/channels/bot'
      path: '/channels/bot'
      fullPath: '/channels/bot'
      preLoaderRoute: typeof AppChannelsBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/meta-ads-tracker': {
      id: '/_app/apps/meta-ads-tracker'
      path: '/apps/meta-ads-tracker'
      fullPath: '/apps/meta-ads-tracker'
      preLoaderRoute: typeof AppAppsMetaAdsTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appSlug': {
      id: '/_app/apps/$appSlug'
      path: '/apps/$appSlug'
      fullPath: '/apps/$appSlug'
      preLoaderRoute: typeof AppAppsAppSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents/$agentId': {
      id: '/_app/ai-agents/$agentId'
      path: '/ai-agents/$agentId'
      fullPath: '/ai-agents/$agentId'
      preLoaderRoute: typeof AppAiAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/instagram/': {
      id: '/_app/channels/instagram/'
      path: '/channels/instagram'
      fullPath: '/channels/instagram/'
      preLoaderRoute: typeof AppChannelsInstagramIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-tools/new': {
      id: '/_app/developers/api-tools/new'
      path: '/new'
      fullPath: '/developers/api-tools/new'
      preLoaderRoute: typeof AppDevelopersApiToolsNewRouteImport
      parentRoute: typeof AppDevelopersApiToolsRoute
    }
    '/_app/channels/whatsapp/success': {
      id: '/_app/channels/whatsapp/success'
      path: '/success'
      fullPath: '/channels/whatsapp/success'
      preLoaderRoute: typeof AppChannelsWhatsappSuccessRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
    '/_app/channels/whatsapp/$channelId': {
      id: '/_app/channels/whatsapp/$channelId'
      path: '/$channelId'
      fullPath: '/channels/whatsapp/$channelId'
      preLoaderRoute: typeof AppChannelsWhatsappChannelIdRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
    '/_app/channels/tiktok/$inboxId': {
      id: '/_app/channels/tiktok/$inboxId'
      path: '/$inboxId'
      fullPath: '/channels/tiktok/$inboxId'
      preLoaderRoute: typeof AppChannelsTiktokInboxIdRouteImport
      parentRoute: typeof AppChannelsTiktokRoute
    }
    '/_app/channels/instagram/$inboxId': {
      id: '/_app/channels/instagram/$inboxId'
      path: '/channels/instagram/$inboxId'
      fullPath: '/channels/instagram/$inboxId'
      preLoaderRoute: typeof AppChannelsInstagramInboxIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChannelsTiktokRouteChildren {
  AppChannelsTiktokInboxIdRoute: typeof AppChannelsTiktokInboxIdRoute
}

const AppChannelsTiktokRouteChildren: AppChannelsTiktokRouteChildren = {
  AppChannelsTiktokInboxIdRoute: AppChannelsTiktokInboxIdRoute,
}

const AppChannelsTiktokRouteWithChildren =
  AppChannelsTiktokRoute._addFileChildren(AppChannelsTiktokRouteChildren)

interface AppChannelsWhatsappRouteChildren {
  AppChannelsWhatsappChannelIdRoute: typeof AppChannelsWhatsappChannelIdRoute
  AppChannelsWhatsappSuccessRoute: typeof AppChannelsWhatsappSuccessRoute
}

const AppChannelsWhatsappRouteChildren: AppChannelsWhatsappRouteChildren = {
  AppChannelsWhatsappChannelIdRoute: AppChannelsWhatsappChannelIdRoute,
  AppChannelsWhatsappSuccessRoute: AppChannelsWhatsappSuccessRoute,
}

const AppChannelsWhatsappRouteWithChildren =
  AppChannelsWhatsappRoute._addFileChildren(AppChannelsWhatsappRouteChildren)

interface AppDevelopersApiToolsRouteChildren {
  AppDevelopersApiToolsNewRoute: typeof AppDevelopersApiToolsNewRoute
}

const AppDevelopersApiToolsRouteChildren: AppDevelopersApiToolsRouteChildren = {
  AppDevelopersApiToolsNewRoute: AppDevelopersApiToolsNewRoute,
}

const AppDevelopersApiToolsRouteWithChildren =
  AppDevelopersApiToolsRoute._addFileChildren(
    AppDevelopersApiToolsRouteChildren,
  )

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlowsRoute: typeof AppFlowsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOutboundRoute: typeof AppOutboundRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppAiAgentsAgentIdRoute: typeof AppAiAgentsAgentIdRoute
  AppAppsAppSlugRoute: typeof AppAppsAppSlugRoute
  AppAppsMetaAdsTrackerRoute: typeof AppAppsMetaAdsTrackerRoute
  AppChannelsBotRoute: typeof AppChannelsBotRoute
  AppChannelsCustomRoute: typeof AppChannelsCustomRoute
  AppChannelsFacebookRoute: typeof AppChannelsFacebookRoute
  AppChannelsLineRoute: typeof AppChannelsLineRoute
  AppChannelsLivechatRoute: typeof AppChannelsLivechatRoute
  AppChannelsTelegramRoute: typeof AppChannelsTelegramRoute
  AppChannelsTiktokRoute: typeof AppChannelsTiktokRouteWithChildren
  AppChannelsWhatsappRoute: typeof AppChannelsWhatsappRouteWithChildren
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppDevelopersApiDocumentationRoute: typeof AppDevelopersApiDocumentationRoute
  AppDevelopersApiToolsRoute: typeof AppDevelopersApiToolsRouteWithChildren
  AppDevelopersMessagesSentByApiRoute: typeof AppDevelopersMessagesSentByApiRoute
  AppDevelopersWebhooksRoute: typeof AppDevelopersWebhooksRoute
  AppInstagramInboxRoute: typeof AppInstagramInboxRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDevelopersIndexRoute: typeof AppDevelopersIndexRoute
  AppSubscriptionIndexRoute: typeof AppSubscriptionIndexRoute
  AppTopUpIndexRoute: typeof AppTopUpIndexRoute
  AppChannelsInstagramInboxIdRoute: typeof AppChannelsInstagramInboxIdRoute
  AppChannelsInstagramIndexRoute: typeof AppChannelsInstagramIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlowsRoute: AppFlowsRoute,
  AppHelpRoute: AppHelpRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOutboundRoute: AppOutboundRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppAiAgentsAgentIdRoute: AppAiAgentsAgentIdRoute,
  AppAppsAppSlugRoute: AppAppsAppSlugRoute,
  AppAppsMetaAdsTrackerRoute: AppAppsMetaAdsTrackerRoute,
  AppChannelsBotRoute: AppChannelsBotRoute,
  AppChannelsCustomRoute: AppChannelsCustomRoute,
  AppChannelsFacebookRoute: AppChannelsFacebookRoute,
  AppChannelsLineRoute: AppChannelsLineRoute,
  AppChannelsLivechatRoute: AppChannelsLivechatRoute,
  AppChannelsTelegramRoute: AppChannelsTelegramRoute,
  AppChannelsTiktokRoute: AppChannelsTiktokRouteWithChildren,
  AppChannelsWhatsappRoute: AppChannelsWhatsappRouteWithChildren,
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppDevelopersApiDocumentationRoute: AppDevelopersApiDocumentationRoute,
  AppDevelopersApiToolsRoute: AppDevelopersApiToolsRouteWithChildren,
  AppDevelopersMessagesSentByApiRoute: AppDevelopersMessagesSentByApiRoute,
  AppDevelopersWebhooksRoute: AppDevelopersWebhooksRoute,
  AppInstagramInboxRoute: AppInstagramInboxRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDevelopersIndexRoute: AppDevelopersIndexRoute,
  AppSubscriptionIndexRoute: AppSubscriptionIndexRoute,
  AppTopUpIndexRoute: AppTopUpIndexRoute,
  AppChannelsInstagramInboxIdRoute: AppChannelsInstagramInboxIdRoute,
  AppChannelsInstagramIndexRoute: AppChannelsInstagramIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCreditAdjustmentRoute: typeof AdminCreditAdjustmentRoute
  AdminModelPricingRoute: typeof AdminModelPricingRoute
  AdminOrgBalanceRoute: typeof AdminOrgBalanceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreditAdjustmentRoute: AdminCreditAdjustmentRoute,
  AdminModelPricingRoute: AdminModelPricingRoute,
  AdminOrgBalanceRoute: AdminOrgBalanceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CreateOrgRoute: CreateOrgRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SelectOrgRoute: SelectOrgRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
